In [49]:
import pandas as pd

In [50]:
s = pd.Series([1,2,3,4,5,6,7])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [51]:
index_day = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
data = [1,2,3,4,5,6,7]

In [52]:
s = pd.Series(data,index = index_day)
s

Monday       1
Tuesday      2
Wednesday    3
Thursday     4
Friday       5
Saturday     6
Sunday       7
dtype: int64

In [53]:
s.mean()

np.float64(4.0)

In [54]:
4*s

Monday        4
Tuesday       8
Wednesday    12
Thursday     16
Friday       20
Saturday     24
Sunday       28
dtype: int64

In [55]:
s+s*2

Monday        3
Tuesday       6
Wednesday     9
Thursday     12
Friday       15
Saturday     18
Sunday       21
dtype: int64

In [56]:
df = pd.DataFrame({"First":s,"Second":s*2,"Third":s*5,"Fourth":s+s})
df

           First  Second  Third  Fourth
Monday         1       2      5       2
Tuesday        2       4     10       4
Wednesday      3       6     15       6
Thursday       4       8     20       8
Friday         5      10     25      10
Saturday       6      12     30      12
Sunday         7      14     35      14

In [57]:
column_names = ["City","Population","Language"]
index_country = ["Japan","India","China","Brazil","Mexico"]

In [58]:
row1 = ["Tokyo",37.4,"Japanese"]
row2 = ["Delhi",28.5,"Tamil"]
row3 = ["Shangai",28.5,"Mandarin"]
row4 = ["Sau Paulo",28.5,"Portuguese"]
row5 = ["Mexico City",28.5,"Spanish"]
data = [row1,row2,row3,row4,row5]

In [59]:
df = pd.DataFrame(data,index=index_country,columns=column_names)
df

               City  Population    Language
Japan         Tokyo        37.4    Japanese
India         Delhi        28.5       Tamil
China       Shangai        28.5    Mandarin
Brazil    Sau Paulo        28.5  Portuguese
Mexico  Mexico City        28.5     Spanish

In [60]:
column_names = ["City","Population","Language"]

In [61]:
cities = ["Tokyo","Mumbai","Shangai","Rio","Mexico City"]
population = [28.3,25.6,46.5,23.5,54.2]
popu_dict = {"City":cities, "Population":population}

In [63]:
df = pd.DataFrame(popu_dict,index=index_country)
df

               City  Population
Japan         Tokyo        28.3
India        Mumbai        25.6
China       Shangai        46.5
Brazil          Rio        23.5
Mexico  Mexico City        54.2