In [1]:
import pandas as pd

In [13]:
df = pd.read_csv("weather.csv")
df

,date,temperature_high,temperature_low,rained,snowed,overcast,comments
0,2021-01-01,4.0,1,1,False,cloudy,happy new year
1,2021-01-02,11.0,2,0,False,sunny,second day
2,2021-01-03,3.0,2,0,False,foggy,third day
3,2021-01-04,6.0,2,0,False,sunny,first business day
4,2021-01-05,4.0,unknown,0,False,cloudy,second business day

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      float64
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(1), float64(1), int64(1), str(4)
memory usage: 377.0 bytes

In [16]:
df["temperature_high"] = df["temperature_high"].astype("int8")

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      int64
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(1), int64(1), int8(1), str(4)
memory usage: 342.0 bytes

In [18]:
df["rained"] = df["rained"].astype("bool")

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      str
 6   comments          5 non-null      str
dtypes: bool(2), int8(1), str(4)
memory usage: 307.0 bytes

In [20]:
df.head()

,date,temperature_high,temperature_low,rained,snowed,overcast,comments
0,2021-01-01,4,1,True,False,cloudy,happy new year
1,2021-01-02,11,2,False,False,sunny,second day
2,2021-01-03,3,2,False,False,foggy,third day
3,2021-01-04,6,2,False,False,sunny,first business day
4,2021-01-05,4,unknown,False,False,cloudy,second business day

In [21]:
df = df.astype({"overcast":"category","comments":"string"})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              5 non-null      str
 1   temperature_high  5 non-null      int8
 2   temperature_low   5 non-null      str
 3   rained            5 non-null      bool
 4   snowed            5 non-null      bool
 5   overcast          5 non-null      category
 6   comments          5 non-null      string
dtypes: bool(2), category(1), int8(1), str(2), string(1)
memory usage: 296.0 bytes

In [22]:
df["overcast"]

0    cloudy
1     sunny
2     foggy
3     sunny
4    cloudy
Name: overcast, dtype: category
Categories (3, str): ['cloudy', 'foggy', 'sunny']

In [23]:
df["temperature_low"] = pd.to_numeric(df["temperature_low"],errors="coerce")

In [24]:
df["temperature_low"]

0    1.0
1    2.0
2    2.0
3    2.0
4    NaN
Name: temperature_low, dtype: float64

In [25]:
df["date"] = pd.to_datetime(df["date"])

In [26]:
df["date"]

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
Name: date, dtype: datetime64[us]