In [4]:
import pandas as pd

In [5]:
left = pd.DataFrame({'col1' : [1,2,3,4,5], 'col2' : ['a','b','c','d','e']})
right = pd.DataFrame({'col1' : [2,3,4,5,6], 'col3' : ['f','g','h','i','j']})

pd.merge(left,right,on='col1', how = 'outer')

   col1 col2 col3
0     1    a  NaN
1     2    b    f
2     3    c    g
3     4    d    h
4     5    e    i
5     6  NaN    j

In [6]:
pd.merge(left,right,on = 'col1', how = 'inner')

   col1 col2 col3
0     2    b    f
1     3    c    g
2     4    d    h
3     5    e    i

In [7]:
pd.merge(left,right,on = 'col1', how = 'right')

   col1 col2 col3
0     2    b    f
1     3    c    g
2     4    d    h
3     5    e    i
4     6  NaN    j

In [8]:
pd.merge(left,right,on = 'col1', how = 'left')

   col1 col2 col3
0     1    a  NaN
1     2    b    f
2     3    c    g
3     4    d    h
4     5    e    i